language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq wget git
  - sh preBuild.sh
install: ./gradlew fatjar
script: ./gradlew check
